@echo off
set dir=public\bible-covers\

:: Master replacements
del %dir%2-corintios.jpg /F /Q
del %dir%galatas.jpg /F /Q
del %dir%efesios.jpg /F /Q
del %dir%filipenses.jpg /F /Q
del %dir%colosenses.jpg /F /Q
del %dir%1-tesalonicenses.jpg /F /Q
del %dir%2-tesalonicenses.jpg /F /Q
del %dir%1-timoteo.jpg /F /Q
del %dir%2-timoteo.jpg /F /Q
del %dir%tito.jpg /F /Q
del %dir%filemon.jpg /F /Q
del %dir%hebreos.jpg /F /Q
del %dir%santiago.jpg /F /Q
del %dir%1-pedro.jpg /F /Q
del %dir%2-pedro.jpg /F /Q
del %dir%1-juan.jpg /F /Q
del %dir%2-juan.jpg /F /Q
del %dir%3-juan.jpg /F /Q
del %dir%judas.jpg /F /Q
del %dir%1-cronicas.jpg /F /Q
del %dir%2-cronicas.jpg /F /Q
del %dir%esdras.jpg /F /Q
del %dir%nehemias.jpg /F /Q
del %dir%ester.jpg /F /Q
del %dir%jueces.jpg /F /Q
del %dir%2-reyes.jpg /F /Q
del %dir%2-samuel.jpg /F /Q
del %dir%marcos.jpg /F /Q
del %dir%lucas.jpg /F /Q

copy %dir%romanos.jpg %dir%2-corintios.jpg /Y
copy %dir%romanos.jpg %dir%galatas.jpg /Y
copy %dir%romanos.jpg %dir%efesios.jpg /Y
copy %dir%romanos.jpg %dir%filipenses.jpg /Y
copy %dir%romanos.jpg %dir%colosenses.jpg /Y
copy %dir%romanos.jpg %dir%1-tesalonicenses.jpg /Y
copy %dir%romanos.jpg %dir%2-tesalonicenses.jpg /Y
copy %dir%romanos.jpg %dir%1-timoteo.jpg /Y
copy %dir%romanos.jpg %dir%2-timoteo.jpg /Y
copy %dir%romanos.jpg %dir%tito.jpg /Y
copy %dir%romanos.jpg %dir%filemon.jpg /Y
copy %dir%romanos.jpg %dir%hebreos.jpg /Y
copy %dir%romanos.jpg %dir%santiago.jpg /Y
copy %dir%romanos.jpg %dir%1-pedro.jpg /Y
copy %dir%romanos.jpg %dir%2-pedro.jpg /Y
copy %dir%romanos.jpg %dir%1-juan.jpg /Y
copy %dir%romanos.jpg %dir%2-juan.jpg /Y
copy %dir%romanos.jpg %dir%3-juan.jpg /Y
copy %dir%romanos.jpg %dir%judas.jpg /Y
copy %dir%1-reyes.jpg %dir%1-cronicas.jpg /Y
copy %dir%1-reyes.jpg %dir%2-cronicas.jpg /Y
copy %dir%1-reyes.jpg %dir%esdras.jpg /Y
copy %dir%1-reyes.jpg %dir%nehemias.jpg /Y
copy %dir%1-reyes.jpg %dir%ester.jpg /Y
copy %dir%1-reyes.jpg %dir%jueces.jpg /Y
copy %dir%1-reyes.jpg %dir%2-reyes.jpg /Y
copy %dir%1-samuel.jpg %dir%2-samuel.jpg /Y
copy %dir%juan.jpg %dir%marcos.jpg /Y
copy %dir%juan.jpg %dir%lucas.jpg /Y
